name: Publish NuGet Package

on:
  push:
    tags:
      - 'v*.*.*'  # Trigger only on version tags like v1.2.3

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore SampleLibrary.csproj

    - name: Build
      run: dotnet build SampleLibrary.csproj --configuration Release --no-restore

    - name: Pack
      run: dotnet pack SampleLibrary.csproj --configuration Release --no-build --output ./nupkgs

    - name: Publish to NuGet
      run: dotnet nuget push "./nupkgs/*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
